colors:
  # Default colors
  primary:
    background: '#292C3E'
    foreground: '#EBEBEB'

  # Cursor colors

  # Normal colors
  normal:
    black:   '#0d0d0d'
    red:     '#FF301B'
    green:   '#A0E521'
    yellow:  '#FFC620'
    blue:    '#1BA6FA'
    magenta: '#8763B8'
    cyan:    '#21DEEF'
    white:   '#EBEBEB'

  # Bright colors
  bright:
    black:   '#6D7070'
    red:     '#FF4352'
    green:   '#B8E466'
    yellow:  '#FFD750'
    blue:    '#1BA6FA'
    magenta: '#A578EA'
    cyan:    '#73FBF1'
    white:   '#FEFEF8'

cursor:
  style:
    blinking: Never
font:
  normal:
    family: Hack
    style: Regular

  bold:
    family: Hack
    style: Bold

  italic:
    family: Hack
    style: Italic

  bold_italic:
    family: Hack
    style: Bold Italic


  size: 12.0

  ligatures: true

  offset:
    x: 0
    y: 0
  glyph_offset:
    x: 0
    y: 0

window:
  dimensions:
    columns: 120
    lines: 35
  padding:
    x: 0
    y: 0
  # scrolling:
  #   # Maximum number of lines in the scrollback buffer.
  #   # Specifying '0' will disable scrolling.
  dynamic_title: true
  dynamic_padding: false
  decoration: full
  history: 1000 
  semantic_escape_chars: ',│`|:"'' ()[]{}<>'
  save_to_clipboard: true
